### ISSUE TITLE
Issue with  Source Block styles

### ISSUE THREAD

**Issue by garmeeh** [Checkfront/react-storybook-addon-chapters#34] opened 2018-04-10 12:51 UTC
Not sure if I'm missing something, but comparing what I have to your example I can't see any differences.

My source blocks look like this:
![image](https://user-images.githubusercontent.com/13333582/38557697-b60507ec-3cc5-11e8-9eee-fbf72397a964.png)

And I am getting the console warnings related to glamorous like this one:

```
glamorous.esm.js:439 glamorous warning: Expected component called "Pre" which uses withTheme to be within a ThemeProvider but none was found.
```

**Comment by brandonellis** [comment] 2018-04-15 22:53
Do you have any code samples you can provide?  I assume fro the provided error you are using a <Pre> tag in your html.

**Comment by vvanmol** [comment] 2018-09-28 08:40
Hello, 

Any updates on this issue ?  I'm also getting several similar Warnings from Components named "CopyButton", "Pre" and "PropVal".

**Comment by brandonellis** [comment] 2018-10-08 18:40
Nothing yet, I spent some time this morning trying to get to the issue.  It seems to be coming from the `addon-info` from Storybook dependency.    I did fix one of the other warnings though.  I have released that on npm with a few minor package updates.

**Comment by vvanmol** [comment] 2018-10-09 12:46
Thanks @brandonellis for your update.
Meanwhile I'm using the Action addon as well and I've set these "glamorous" warnings as excluded patterns so they don't show up for regular users.  Only developers who require the actual DevTools of their browser see them in the actual Console...

**Comment by brandonellis** [comment] 2018-10-10 01:14
What was your approach, or how did you do this? You open to creating a PR for it here in this repo?

**Comment by brandonellis** [comment] 2018-12-04 17:32
Looks like the branch I have for Storybook V4 will fix the `glamourous` issues.  Would need confirmation for your experiences though.

**Comment by vvanmol** [comment] 2018-12-29 15:10
Hi @brandonellis 

Sorry for the late reply.  I can't really open a PR regarding the handling I've done to discard these warnings as it is done by configuring the Storybook Action addon.  

On Monday I'll update my project's dependencies and I'll let you know if the warnings are gone.

**Comment by vvanmol** [comment] 2019-01-18 14:47
Hi @brandonellis 

Late reply (again) but I confirm the issue is indeed fixed once I upgraded to Storybook V4.

**Closed** 2019-01-21 21:43 UTC
